import time
import webbrowser
#Hacking courses only
def hacking_courses():
    webbrowser.open('https://www.udemy.com/payment/checkout/?boId=931384&boType=course&couponCode=JERRYBANFIELD')
    time.sleep(5)
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=687824&couponCode=freebee')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=846664&boType=course&couponCode=FREEBIES')
    time.sleep(5)
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=896414&couponCode=FREEBIES')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=916828&couponCode=FREEBIES')
    time.sleep(5)
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=415074&boType=course&couponCode=WOO052816')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=437490&couponCode=WOO052816')

#Programming courses only
def Programming_courses():
    webbrowser.open('https://www.udemy.com/payment/checkout/?boId=648120&boType=course&couponCode=free215')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=499632&couponCode=expro')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1262952&couponCode=PBCUDEMYGROUPS')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1027342&couponCode=LEARNFREE')
    time.sleep(5)
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=949766&couponCode=JERRYBANFIELD')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=808912&boType=course&couponCode=JavaSwing100OFF')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1324998&couponCode=FREECOURSEGD')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=846578&couponCode=FREEWEBDEV81217')
    time.sleep(5)
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=513018&couponCode=CCDX-FREE')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=1288400&boType=course&couponCode=PROMOCOUPONS24.COM')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=674646&couponCode=FREEWEBDEV8124')
    time.sleep(5)
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=1093734&boType=course&couponCode=FORFREE')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=992114&boType=course&couponCode=COUPONFREE')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=1327920&boType=course&couponCode=FREEPYTHON2017')
    time.sleep(5)
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=1305806&boType=course&couponCode=BBHFREE')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1312228&couponCode=BANGLADESH')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1189566&couponCode=FREEGSAPP')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=1326798&boType=course&couponCode=FACELIMITED')

#Lifestyle Courses only
def Lifestyle_courses():
    webbrowser.open('https://www.udemy.com/payment/checkout/?boId=1114784&boType=course&couponCode=FREEJOE')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=746700&couponCode=FREEFORA')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=302400&couponCode=free_UDEMY_courses_FBgroup')
    time.sleep(5)
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=1329878&boType=course&couponCode=CRYPTOFREE2466')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=852058&boType=course&couponCode=BLACKFRIDAYFREE')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=696284&couponCode=24_HOUR_FREE')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1312962&couponCode=VIPLOOT')
    time.sleep(5)
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1321026&couponCode=STHFREE')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1281296&couponCode=WELCOME')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1258432&couponCode=FREE13')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=980520&boType=course&couponCode=FIVERRBOUHADDA3')

#Marketing Courses only
def Marketing_courses():
    webbrowser.open('https://www.udemy.com/payment/checkout/?boId=941486&boType=course&couponCode=FBADS0')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1155172&couponCode=FB-BOTS')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1149554&couponCode=FREE4BLACKHAT2')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=1128336&boType=course&couponCode=AHREFSINSIDER')
    time.sleep(5)
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=982152&boType=course&couponCode=YOUCOUP')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=407294&boType=course&couponCode=REVIEWAPPRECIATED')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=876414&couponCode=FREE-20000')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=900460&boType=course&couponCode=FREE-10000')
    time.sleep(5)
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=557800&couponCode=BBHAUG16')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=902710&couponCode=FREE-10000')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=1320476&boType=course&couponCode=FREENOW')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=1304664&boType=course&couponCode=FIND_YOUR_NICHE')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=1316490&boType=course&couponCode=FREE13')
    time.sleep(5)
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1322628&couponCode=BLESSED')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1322170&couponCode=FREENOW')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1324754&couponCode=LAUNCH1')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=1261178&boType=course&couponCode=REALDISCOUNTAUG')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=1227276&boType=course&couponCode=REALDISCOUNTAUG1')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1324754&couponCode=LAUNCH2')

def Designing_Courses():
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=1258402&boType=course&couponCode=FREE13')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=1321414&boType=course&couponCode=FREE13')
    time.sleep(5)
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=886644&couponCode=FREEINSTRUCT')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=951060&boType=course&couponCode=FREEWEBDEV8122')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1262952&couponCode=PBCUDEMYGROUPS')
    time.sleep(5)
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1326798&couponCode=FACELIMITED')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1331988&couponCode=LAUNCHFREE')

#All of the Above Courses
def All_Courses():
    Marketing_courses()
    time.sleep(5)
    hacking_courses()
    time.sleep(5)
    Lifestyle_courses()
    time.sleep(5)
    Programming_courses()
    time.sleep(5)
    Designing_Courses()
    time.sleep(5)
    #Note Some Bonus Courses
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=809994&boType=course&couponCode=WONDER55P9')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1027212&couponCode=TTTCC2D-100OFF')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=1078568&couponCode=SFMLTTT-CFREE4')
    time.sleep(5)
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=1208228&boType=course&couponCode=FORFREE')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boId=1328962&boType=course&couponCode=THIS4FREE')
    webbrowser.open_new_tab('https://www.udemy.com/payment/checkout/?boType=course&boId=700886&couponCode=FREECOURSE2')
